### ISSUE TITLE
i could not build  Failed to resolve entry for package "astro-biome". The package may have incorrect main/module/exports specified in its package.json.

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [NikolaRHristov/AstroBiome#39]
```
[astro] Unable to load your Astro config

 error   Failed to resolve entry for package "astro-biome". The package may have incorrect main/module/exports specified in its package.json.
  File:
    /home/ende/DEV/sup/test/uno66/astro.config.mjs
  Stacktrace:
Error: Failed to resolve entry for package "astro-biome". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (file:///home/ende/DEV/sup/test/uno66/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28725:11)
    at resolvePackageEntry (file:///home/ende/DEV/sup/test/uno66/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28722:5)
    at tryNodeResolve (file:///home/ende/DEV/sup/test/uno66/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28453:20)
    at Context.resolveId (file:///home/ende/DEV/sup/test/uno66/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28212:28)
    at Object.resolveId (file:///home/ende/DEV/sup/test/uno66/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44276:64)
    at async TransformContext.resolve (file:///home/ende/DEV/sup/test/uno66/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:43992:23)
    at async normalizeUrl (file:///home/ende/DEV/sup/test/uno66/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:41836:34)
    at async file:///home/ende/DEV/sup/test/uno66/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:41998:47
    at async Promise.all (index 2)
    at async TransformContext.transform (file:///home/ende/DEV/sup/test/uno66/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:41914:13)

Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
```
![image](https://github.com/NikolaRHristov/AstroBiome/assets/45184918/10def433-7f3f-4cfc-8d89-fd8f42deef87)

**Comment by NikolaRHristov** [comment]
Fixed in [0.0.3](https://github.com/NikolaRHristov/AstroBiome/releases/tag/v0.0.3)
